# Generated by Django 3.0.8 on 2020-07-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_json', models.CharField(max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=300)),
                ('city', models.CharField(default='', max_length=300)),
                ('state', models.CharField(default='', max_length=300)),
                ('zip_code', models.CharField(default='', max_length=300)),
                ('phone', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
